name: Daily NBA Story Pull (Pages)

on:
  schedule:
    - cron: "0 11 * * *"  # daily 11:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r pipeline/requirements.txt

      - name: Run pipeline (scrape & write)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python pipeline/nba_news_pipeline.py
          echo "Pipeline complete"

      - name: Commit daily content
        run: |
          git config user.name "nba-auto-bot"
          git config user.email "bot@users.noreply.github.com"
          git add -A
          git commit -m "Daily NBA update: $(date -u +'%Y-%m-%d')" || echo "No changes to commit"
          git push || true

      - name: Upload Pages artifact (site/)
        uses: actions/upload-pages-artifact@v3
        with:
          path: nba/site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
